### ISSUE TITLE
Airplay

### ISSUE THREAD

**Issue by Styopa12** [mkulesh/onpc#207] opened 2021-01-23 20:07 UTC
How do you connect to Airplay? Under NET I cannot find.

**Comment by mkulesh** [comment] 2021-01-23 21:33
Hi @Styopa12,
the support of AirPlay depends on the receiver model. For example, in my Onkyo NS-6170 I have it in the NET:
![airplay](https://user-images.githubusercontent.com/30557348/105614655-ea437b00-5dca-11eb-98db-427b47c69997.png)

Which model do you have? Does the official Onkyo app show the AirPlay for your device?

**Comment by Styopa12** [comment] 2021-01-23 21:44
Hello

I have a TX-RZ630. Airplay does appear on the onkyo controller app in the NET 
![7760D52D-4401-407D-8B82-887A22AD6E39](https://user-images.githubusercontent.com/77899253/105614854-34f8cf00-5d9a-11eb-908a-486eb65dea4f.png)

**Comment by Styopa12** [comment] 2021-01-23 21:46
Oh...and here is snapshot from your app (BTW loving this...been looking for an alternative!!)
![858B4FCB-9545-4CDA-A104-AC51FE18027F](https://user-images.githubusercontent.com/77899253/105614914-84d79600-5d9a-11eb-9c1c-7e256b7f3ee0.png)

**Comment by mkulesh** [comment] 2021-01-23 21:52
Hi @Styopa12,
the label "items: 7/12" means that some networks services are disabled in the app settings. Could you please open app settings, select "Network services" and ensure that AirPlay is selected:
![airplay2](https://user-images.githubusercontent.com/30557348/105615027-a9009a80-5dcd-11eb-90e3-8721810f7744.png)

**Comment by Styopa12** [comment] 2021-01-23 22:01
I had checked there before and it is not listed ...this is everything 
![08422630-16B7-4A52-9390-0BCC9F211C7E](https://user-images.githubusercontent.com/77899253/105615171-8bffa380-5d9c-11eb-87ad-755311ccdcdd.png)

**Comment by mkulesh** [comment] 2021-01-23 22:11
strange... Could you please open app settings, activate "Developer options", than select "About" from the navigation menu, select "Receiver information" tab, copy text to clipboard and send it me per email on mikhail.kulesh@gmail.com?

**Comment by Styopa12** [comment] 2021-01-23 22:18
done

**Comment by mkulesh** [comment] 2021-01-23 22:31
Hi @Styopa12,
thank you, I see the problem and can try fix it. Before the fix is released I suggest a workaround. I tried it with my NS-6170 and iPad and this workaround works. If I select my player in the iOS sound settings and start playing something on iPad (for example in VLC), the player automatically switches the channel to AirPlay:
<img width="426" alt="airplay" src="https://user-images.githubusercontent.com/30557348/105615743-2c70ba80-5dd3-11eb-9ec7-68c4c87bc6e7.png">

**Comment by Styopa12** [comment] 2021-01-23 22:34
Thanks - 
I noticed that it does work and defaults when i turn it on but i cannot choose - so if I navigate away from airplay . I can get back to it . .

Will try and look forward to updated release - thanks again & keep up the good work

**Comment by mkulesh** [comment] 2021-01-23 22:34
The problem is that TX-RZ630 has a different code for AirPlay. The standard code is "18", but TX-RZ630 uses code "44":
<netservice id="44" value="1" name="AirPlay" zone="07" enable="07" />
The support of both codes for AirPlay shall be added.

**Comment by Styopa12** [comment] 2021-01-23 22:35
i Spasibo bolshoi . . krutoi app!

**Comment by Styopa12** [comment] 2021-01-23 22:42
Gotcha...great resource
Спасибо!

Sent from my iPhone

On Jan 23, 2021, at 17:35, Mikhail Kulesh <notifications@github.com> wrote:

﻿

The problem is that TX-RZ630 has a different code for AirPlay. The standard code is "18", but TX-RZ630 uses code "44":

The support of both codes for AirPlay shall be added.

**Comment by mkulesh** [comment] 2021-01-24 12:06
Hi @Styopa12,
I hope that the problem is now fixed. However, it takes some time in order to publish new release in App Store. Do you have any Android device? If yes, could you please install the Android version of the app and test how does it work?
The APK is here: https://github.com/mkulesh/onpc/blob/autobuild/autobuild/onpc-v2.9.2-release.apk
I let you known when iOS build will be available on TestFligh
Если будут вопросы, пишите на mikhail.kulesh@gmail.com

**Comment by Styopa12** [comment] 2021-01-24 17:33
Hello...only IOS...will check when updated. Thanks

Sent from my iPhone

On Jan 24, 2021, at 07:06, Mikhail Kulesh <notifications@github.com> wrote:

﻿

Hi @Styopa12<https://github.com/Styopa12>,
I hope that the problem is now fixed. However, it takes some time in order to publish new release in App Store. Do you have any Android device? If yes, could you please install the Android version of the app and test how does it work?
The APK is here: https://github.com/mkulesh/onpc/blob/autobuild/autobuild/onpc-v2.9.2-release.apk
I let you known when iOS build will be available on TestFligh
Если будут вопросы, пишите на mikhail.kulesh@gmail.com<mailto:mikhail.kulesh@gmail.com>

**Comment by mkulesh** [comment] 2021-01-24 22:08
Hi @Styopa12,
the fixed version (2.9.2) is now available on TestFlight: https://testflight.apple.com/join/oV5j2iMh
Please let me know how does it work after fix.

**Comment by Styopa12** [comment] 2021-01-24 23:01
Boom
Well done Mish
Thanks

Sent from my iPhone

On Jan 24, 2021, at 17:08, Mikhail Kulesh <notifications@github.com> wrote:

﻿

Hi @Styopa12<https://github.com/Styopa12>,
the fixed version (2.9.2) is now available on TestFlight: https://testflight.apple.com/join/oV5j2iMh
Please let me know how does it work after fix.

**Comment by mkulesh** [comment] 2021-02-07 12:22
Released in version 2.9.5 (iOS) and 2.9.4 (Android)

**Comment by mkulesh** [comment] 2021-02-07 12:23
To be fixed in 1.22

**Comment by mkulesh** [comment] 2021-02-11 13:40
Released in version 1.22

**Closed by mkulesh** 2021-02-11 13:41 UTC
Labels: bug
