### ISSUE TITLE
R-N855: Sound profile flips between "DIRECT" and "All CH STEREO" everytime I open the app

### ISSUE THREAD

**Issue by WalterFaber** [mkulesh/onpc#109] opened 2019-12-22 14:12 UTC
Dear Mikhail,

I've already reported a similar issue in a previous version (see #69) . But this time, it is different as I can reproduce the issue easily.

Version: 1.7
Onkyo Device: R-N855

**Steps to reproduce:**
1. Set the sound profile to "ALL CH STEREO"
2. Close the app or just send to background
3. Open the app
4. Close the app or just send to background
5. Open the app
... and so on

**Actual:**
After steps 3. the sound profile is set to "DIRECT"
After step 5. the sound profile is set to "ALL CH STEREO"
It changes the sound profile back and forth every time I open the app

**Expected:**
Sound profile must not change automatically once the app is closed and opened again 

**Remarks:**
Until today, I used version 1.2. This issue doesn't exist in this old version and just appeared after the upgrade to 1.7

**Comment by mkulesh** [comment] 2019-12-22 19:48
Hi @WalterFaber,
some people wrote me that a new firmware version for R-N855 exists and, if this firmware is installed R-N855 works more stable and, as a result, no flip-flop between "DIRECT" and "ALL CH STEREO" is more observed. Do you already have the latest firmware on your R-N855?

**Comment by WalterFaber** [comment] 2019-12-22 20:48
Hi @mkulesh,
thank you for your quick response and for pointing me to the new firmware.
Actually, I'm not using the latest firmware and I wasn't even aware that it has been released.

My current firmware is: 2120-3000-0000-0010
Latest firmware released in Nov. 2019: 2140-5000-0000-0011

However, there might be some very serious bugs in the new firmware, see:
[http://www.hifi-forum.de/viewthread-272-6905.html](http://www.hifi-forum.de/viewthread-272-6905.html)

- Post No. 8 states that Onkyo has confirmed the issue.
- Post  No. 9 indicates that R-N855 is probably also affected even if the initial post refers to another Onkyo product)

I will have an eye on that issue and once they fixed the bugs in their latest release, I will upgrade my receiver  accordingly. After that, I will share my experiences here.
In the meantime, I downgrade your app to 1.2 as I really don't want to brake my R-N855 and App version 1.2 was already quite good - close to perfect :)!

**Comment by mkulesh** [comment] 2019-12-23 11:27
Hi @WalterFaber,

I think it is a good idea to keep v.1.2. The major deference between v.1.2 and the latest version is that the v.1.7 supports multi-room and receiver search on Android 10. If these points are not important for your, v.1.2 is a good choice. For me is however interesting in which version this regression appears. If you have time could you please try different versions (the list of all releases here: https://github.com/mkulesh/onpc/releases) and write me in which version the handling of DIRECT mode was broken?

If you have any iOS device (iPad, iPod or iPhone), could you also try this iOS beta version: https://testflight.apple.com/join/oV5j2iMh
May be this version works better...

**Comment by WalterFaber** [comment] 2019-12-23 23:32
Hi @mkulesh,
I tested all versions from 1.2 to 1.7 and was able to identify 1.6 which clearly has broken handling of DIRECT mode. 1.5 and below is fine (except #69 - but this issue appears only under certain conditions which I've never been able to reproduce).
Ok, so I'll keep 1.5 for the time being.

Unfortunately, I don't have an Apple device - so I can't test the iOS beta.
However, if you need someAandroid testing, I'm always happy to help. Just let me know if you need a test.

**Comment by mkulesh** [comment] 2020-01-04 14:28
Regression due to commit https://github.com/mkulesh/onpc/commit/ab38ea48475f476ecadfb147dc0a583118543a3f

As a solution, we will try to partially revert this commit

**Comment by mkulesh** [comment] 2020-01-04 15:32
Hi @WalterFaber,

I reverted the commit from the release 1.6 that I think is the reason for such a regression. Could you please test the latest auto-build from here: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.8-debug.apk

**Comment by WalterFaber** [comment] 2020-01-05 12:58
Hi @mkulesh,
I've just installed onpc-v1.8-debug.apk.
The issue is fixed. i.e. the application behaves similar to v1.5.

Just for your Info:
If I open the app and my receiver is already running, the following happens
1. the app connects to my receiver
2. the receiver display shows "direct off" for ~ 1 second
3. Sound gets interrupted for ~ 1 second

-> it's not an issue for me
-> this has been the case in all versions I've seen so far
-> I just want to let you know in detail what happens in case it behaves different with your receiver
-> I know someone else has opened an issue because of that

Thank you again for your the great app.

**Comment by mkulesh** [comment] 2020-01-10 17:23
Released in v.1.8

**Closed by mkulesh** 2020-01-10 17:23 UTC
Labels: bug
