### ISSUE TITLE
Device setting "Display Off" is missing for Pioneer receivers

### ISSUE THREAD

**Issue by MoonMaker** [mkulesh/onpc#256] opened 2022-05-08 19:28 UTC
Display off and Option to change it back is gone.
![Screenshot_20220508-212703_Enhanced_Music_Controller](https://user-images.githubusercontent.com/1302904/167312486-b61ac45b-2bf6-4ece-af37-e09c365b4fed.png)

**Comment by mkulesh** [comment] 2022-05-10 18:53
Hi @MoonMaker,
thank you for the issue. Could you please provide more details when it happened? Did the Dimmer Level disappear after the app was updated or after the Pioneer firmware update?

I uploaded some previous versions of the app on https://onedrive.live.com/?authkey=%21ANJ7%5FJB5cy7S9tU&id=85210F986F87ACDD%21118&cid=85210F986F87ACDD

Could you please install any previous APK manually and check whether the Dimmer Level option is available?

If not, could you please collect the app log as follows:
- Open "Settings" dialog and activate the "Developer options" at the end of the settings list
- Close the app
- Open the app again and keep it opened
- From Pioneer Remote Control (not from the app) change the Display off/on and loop over all available dimmer levels
- In the app, open "About" window from the app menu and select the tab "Latest Logging" 
- Press "Copy to clipboard" button
- Send the content of whole copied clipboard per e-mail on mikhail.kulesh@gmail.com
- Open "Settings" dialog again and DISABLE the "Developer options"
This log may help me to fix this problem.

**Comment by mkulesh** [comment] 2022-05-10 20:46
Hi @MoonMaker,
thank you for the log. it was really helpful. I found the problem. Pioneer uses a special code for "Device Off" setting that differs from the corresponding code of Onkyo devices and, therefore, was missing in my implementation (since I only tested the app on Onkyo devices). Now, I added this code and hope that the problem is solved. Could you please download and install new build MusicControl-v2.11.2-android.apk from https://onedrive.live.com/?authkey=%21ANJ7%5FJB5cy7S9tU&id=85210F986F87ACDD%21118&cid=85210F986F87ACDD and test how it now works?

**Comment by mkulesh** [comment] 2022-05-10 20:50
to be merged into free version

**Comment by MoonMaker** [comment] 2022-05-10 20:58
Hi,

congrats, works perfectly.

Cheers

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by mkulesh** [comment] 2022-06-10 19:53
Released in version 2.11.2

**Comment by mkulesh** [comment] 2022-06-10 19:55
Hi @MoonMaker 
Release 2.11.2 is now submitted to Google Play and may be available for download within the next couple of days

**Comment by mkulesh** [comment] 2022-06-12 18:41
Released in version 1.26

**Closed by mkulesh** 2022-06-12 18:41 UTC
Labels: bug
