### ISSUE TITLE
onkyo TX-NR609 no Information about device even if it is connected..

### ISSUE THREAD

**Issue by smartboart** [mkulesh/onpc#113] opened 2020-01-02 17:17 UTC
Hello, nice app but not fully Wirkung with onkyo TX-NR 609..see picture...with my other receiver it is Wirkung great.
![Screenshot_20200102-181638_Enhanced Controller for Onkyo and Pioneer](https://user-images.githubusercontent.com/38385805/71681092-16d5c080-2d8c-11ea-98b9-589e0a8f1c9f.jpg)
![Screenshot_20200102-181649_Enhanced Controller for Onkyo and Pioneer](https://user-images.githubusercontent.com/38385805/71681105-1dfcce80-2d8c-11ea-9baa-1412f453020e.jpg)

**Comment by mkulesh** [comment] 2020-01-04 16:57
Hi @smartboart,

This TAB (Gerät) shows the information received via so called "Receiver Information" message. As I see in the protocol description, this message is not supported by TX-NR 609. It means the app behavior in this case is as desired. 

On other hand I agree that empty device information section is confusing. I can completely hide this panel if  "Receiver Information" message is missing. That do you think about this solution?

**Comment by smartboart** [comment] 2020-01-06 11:44
Hello...this would be a good solution.. but in general i would prefer that this nice app also would work with my receiver TX-NR609...is There a Chance that you can add this receiver ?

**Comment by mkulesh** [comment] 2020-01-06 21:19
Hi @smartboart,

I do not have in my app any filters by receiver model. The app just communicates with the receiver using so called ISCP protocol (Integra Serial Communication Protocol) developed by Onkyo. The problem is that different Onkyo receivers support this protocol in different ways. For example, previous models only support a part of whole protocol. I continuously try to add workarounds in the app in order to support these receiver models, but it is not always easy. Could you please write me in more details that exactly functionality does not work for you?

**Comment by mkulesh** [comment] 2020-02-11 22:19
Hi @smartboart,

I fixed this problem. Now, the DEVICE tab shall looks for your device like this:
![device-2020-02-11-230837](https://user-images.githubusercontent.com/30557348/74284684-8d1ef880-4d24-11ea-9e94-0480af58fec4.png)

I.e, the whole panel "Device info" shall be not more visible. 

Please also look at https://github.com/mkulesh/onpc/issues/125.
I think this issue can also be observed on your device.

Could you please install the latest nightly build https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.10-debug.apk and test how it now works for you?

**Comment by smartboart** [comment] 2020-02-21 23:01
Sorry for late reply... I was not able to test it yet... Had a long business trip... Will test it soon.... Thanks for working on this issue. ..

**Comment by mkulesh** [comment] 2020-02-22 10:31
Hi @smartboart, no problem for me since I also have a lot of short business trips last weeks. Thanks for your effort!

**Comment by smartboart** [comment] 2020-02-23 08:59
Hello, thanks for this nice app....Today i was able to test  alittle bit...Now it works like sharm with my onkyo TX-NR609...Only one issue / problem i have found in the media menue....When i choose Net and the Favorites to select one of my favourite Internet Radio channels, nothing happens....
The favourites are shown but not selectable...If i select it with the Onkyo app, it willplay my favourite...Also your app changes to the playmodus then...
If i will find out more, i will let you know....

**Comment by mkulesh** [comment] 2020-02-23 20:23
Hi @smartboart,
to analyze the problem with Favorites list, I need the application logging.
could you please collect and send me this logging as follows:
- Download and install the latest nightly build: https://github.com/mkulesh/onpc/blob/autobuild/autobuild/onpc-v1.10-debug.apk
- Open "Settings" dialog and activate the "Developer options" at the end of the settings list
- Go back to the App. An application menu (three dots on the right of toolbar) appears
- In the App, select Net and than Favorites. Press several times on different favorite items
- Press the application menu button and select the menu "Latest logging"
- Long press on the text and than press "Select All" from context menu
- Copy this text in buffer ("Copy" from the context menu) and send it me per e-mail on mikhail.kulesh@gmail.com
- Open "Settings" dialog again and DISABLE the "Developer options"

**Comment by mkulesh** [comment] 2020-03-15 15:18
Released in iOS Release 2.2

**Closed by mkulesh** 2020-03-15 15:18 UTC
Labels: bug
