### ISSUE TITLE
Enable sorting within music network services

### ISSUE THREAD

**Issue by derHSE** [mkulesh/onpc#228] opened 2021-02-26 13:53 UTC
Hi, maybe as an enhancement it would be nice to have for example "My Artists" displayed in a sorted order within Deezer.

Today I go to NET / Deezer / My Music / My Artists and see all my favorite artists in an unsorted way. Would be nice to have them sorted. Also applies to the other submenus, too (My Albums...)

Maybe suitable for other network music services, too (Spotify, Tidal...)

**Comment by mkulesh** [comment] 2021-02-28 16:03
Hi @derHSE,
thank you for the idea. Unfortunately it is not too easy. Currently, such a sorting is only available in the DLNA service since DLNA supports different kinds if sorting:
<img width="594" alt="Screenshot 2021-02-28 at 16 55 47" src="https://user-images.githubusercontent.com/30557348/109424866-051a9800-79e6-11eb-9617-2084d7d8e093.png">
Bit this sorting is performed by the receiver.
It is no problem to allow this sort button (shown on the screenshot above) in whole MEDIA tab. The problem is that the order of items in the app and in the receiver will be different and the playback order (as done by receiver) will differ from the order of items in the app. It will have an effect of "random" playback when items are sorted alphabetically. It is not too good. May be I can add an application setting like "Allow sort in MEDIA tab" that is disabled by default. That do you think about it?

**Comment by derHSE** [comment] 2021-02-28 18:15
Yup, that sounds difficult to solve. I think in the above example from you, sorting especially within an album should not be done. It is needed only in "My Albums", "My Artists" and so forth. But if I get you right, this is not so easy. What about inserting this "sorting icon" only in "My Albums" and so on?

**Comment by mkulesh** [comment] 2021-03-01 22:06
Hi @derHSE,
At least TuneIn has own sort logic and I am currently not sure whether it is a good idea to change it. I have no Spotify, Tidal or Amazon Music accounts and currently not able to check these services. Therefore I prefer to be a little bit conservative and only expand Deezer. A also checked DLNA and it always sort folders alphabetically.

I now added alphabetical sorting of all folders that do not have any playable items in Deezer (without a button). Now it always sorted alphabetically:
![Screenshot from 2021-03-01 22-54-35](https://user-images.githubusercontent.com/30557348/109564640-a2a6c200-7ae1-11eb-9d19-0a5c8c8ac759.png)
Could you please download and install the latest build for premium version and test how it does it work for you?
APK is here: https://github.com/mkulesh/onpc/raw/autobuild/release/MusicControl-v2.10.1-android.apk

That do you think that is better: sort alphabetically always or add a button? From my point of view the first option is more comfortable.

**Comment by derHSE** [comment] 2021-03-02 22:28
I also only have Deezer at the start, sometimes I borrow a Spotify account for testing :-) 

I think this version is better in terms of sorting for most cases. In my opinion, it doesn't need a button.

There is only one place where I would like to have more choice: MEDIA / NET / Deezer / My Music / My Albums:
Here the following sorting options would be good
- By album name (as it is now).
- By artist, then album name
- By artist, then year, then album name (supreme discipline :-) )

Possibly difficult to programme, isn't it?

Thanks already!

**Comment by mkulesh** [comment] 2021-03-03 21:06
Hi @derHSE 
thank you for testing. In my Deezer / My Music / My Albums I have no year. Therefore I think it is impossible to use year as a sort criteria. But I can try to add a "sort mode" button for "My Albums" folder. This button will switch between "By album name" and "By artist, then album name" since there is a separator "/" between album and artist:

<img width="604" alt="Screenshot 2021-03-03 at 22 05 25" src="https://user-images.githubusercontent.com/30557348/109872337-969b3b80-7c6c-11eb-8965-731f4e3a4f2f.png">

I think I need a couple of days for it. I let you known when new build will be available for testing.

**Comment by mkulesh** [comment] 2021-03-05 21:49
Hi @derHSE, please download and install https://github.com/mkulesh/onpc/raw/autobuild/release/MusicControl-v2.10.1-android.apk again. In this new build you will find a new button "Sort" in the right of the button "Filter" when the current directory is "My Album". This allows switch between "By album name" and "By artist, then album name":
<img width="654" alt="Screenshot 2021-03-05 at 22 46 00" src="https://user-images.githubusercontent.com/30557348/110177204-e1e85200-7e04-11eb-8837-db8f8240dcfc.png">

**Comment by derHSE** [comment] 2021-03-06 22:50
Thank you for your work so far.

If I understood you correctly, you don't have a "Year" field available? That means you don't communicate with Deezer, but only with what the Onkyo gives you?  

The function is well done, thank you for that. But I would still have one suggestion: if you sort the albums alphabetically (standard) then you show them with the scheme "Album / Artist", that's good.

But if you now sort the albums by artist with the new function, then it would also be correct to display them with the scheme "Artist / Album" (and not vice versa), wouldn't it? What do you mean?

**Comment by mkulesh** [comment] 2021-03-07 21:54
yes, the "Year" field is not propagated by the receiver to the client. And yes, the app communicates only with the receiver via a unified XML-based protocol. This unified protocol is used for all network services supported by the receiver. If it is interesting for you please look at this document: https://github.com/mkulesh/onpc/blob/master/doc/ISCP_AVR_146.xlsx
The sheet "CMND(NET USB)" contains the message "NLA". This message is send by the receiver to the app and contains fully formatted and pre-sorted list of item that shall be just shown in the media list. 
Thank you for the idea to swap Album and Artist. It is not too easy since I shall parse and update whole media list with a good performance. But I will try to implement it.

**Comment by mkulesh** [comment] 2021-03-08 19:27
Hi @derHSE,
A swap Album and Artist is done, please download and install APK again: https://github.com/mkulesh/onpc/raw/autobuild/release/MusicControl-v2.10.1-android.apk
<img width="714" alt="Screenshot 2021-03-08 at 20 23 20" src="https://user-images.githubusercontent.com/30557348/110370918-97f1ad00-804c-11eb-9450-83e4d5525539.png">

**Comment by derHSE** [comment] 2021-03-09 06:57
...works like a charm! I think it is solved in the best possible way.

**Comment by mkulesh** [comment] 2021-04-12 20:53
Released in version 2.10.1

**Closed by mkulesh** 2021-04-12 20:53 UTC
Labels: enhancement
