### ISSUE TITLE
FlareConnect without wifi

### ISSUE THREAD

**Issue by dlandr** [mkulesh/onpc#145] opened 2020-04-22 18:39 UTC
We can connect one device or other without wifi but we can't synchronize 2 devices with FlareConnect without wifi.

**Comment by mkulesh** [comment] 2020-05-15 20:00
Hi @dlandr,
The issue is implemented. Now, it shall be possible to group favorite devices, listed in the navigation drawer. However, you shall ensure that each favorite device has so called MAC address stored with it. This MAC address is used by Onkyo FlareConnect in order to group devices. 

Please do following:
- Connect to each favorite device that you already have in the navigation drawer (it shall be done once after application update)
- After you connected to each, open "Edit connection" dialog and ensure that **each device** have a new filed "MAC Address" filled like this:
![mac_address](https://user-images.githubusercontent.com/30557348/82090776-7e1a5e80-96f6-11ea-9fd7-a221d8f797ab.png)
- If it is not filled, you can find this information in the settings of your receiver, section "System Info"
![IMG_20200515_215528](https://user-images.githubusercontent.com/30557348/82091115-1a446580-96f7-11ea-8afd-7c3b3afb0e47.jpg)
- If "MAC Address" is properly filled for all devices from your group, you will see all these devices in the "Group devices" dialog bot in WiFi and non-WiFi mode:
![grou_devices](https://user-images.githubusercontent.com/30557348/82091376-8626ce00-96f7-11ea-8cf1-251b9515ea57.png)

**Comment by mkulesh** [comment] 2020-06-23 21:20
Released in iOS version 2.4

**Closed by mkulesh** 2020-06-23 21:20 UTC
Labels: enhancement
