### ISSUE TITLE
Refresh problem after rotating screen

### ISSUE THREAD

**Issue by iamchriscool** [mkulesh/onpc#58] opened 2019-05-01 06:23 UTC
After rotating my device the screen get refreshed. If I am in the radio station list, the list is afterwards empty.
Rotating the screen several times again brings back the station list.
Also the Listen tab is not correctly refreshed. The buttons and the current radio channel disappear after rotation.

**Comment by mkulesh** [comment] 2019-05-02 19:24
Hi @iamchriscool, thank you for reporting the issue. Which Android version do you use?

**Comment by iamchriscool** [comment] 2019-05-02 20:54
LinagesOS 15 (Android 8) but I also have the same problem on my tablet that is running on Android 5. For me it doesn't look like a problem that is related to the Android version. I think you can reproduce the problem on any Android version by just rotating your device while you are in the station list of radio channels.

**Comment by quelbs** [comment] 2019-05-04 21:14
Hi, I was able to reproduce this issue once, but since then it just works fine for me. It may be a network connectivity issue, as the list is reloaded from the receiver on screen rotation.

One interesting thing I realized is, on rotation the current station is not always marked with the green arrow, so there might be some race conditions when displaying the list.

**Comment by iamchriscool** [comment] 2019-05-04 21:38
Maybe it's a race condition, maybe it's a problem of the receiver, because with me it is on all my devices a problem. I think it could be all solved by just not reloading things from the receiver when rotating the device. If the data of the current visible screen is cached and reused when the screen is drawn again after rotation, it's first much faster and would maybe solve the problem.
Could that be a solution?

**Comment by mkulesh** [comment] 2019-05-05 10:36
Hi @iamchriscool, thank you for details. Actually, previously in the prototype I implemented the full state collection/install, but found the problem that the cover image is usually too big and Android produces an exception that state can not be collected within given time period (this is a new Android limitation since version 6.0). It means the cover image shall be always downloaded and, therefore, I decided to always perform the re-connect and full refresh instead to collection/install state and than only download the cover image.

Could you please collect the log from the app as follows:
- Install the latest nightly build from here: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.1-debug.apk
Since this build is not signed, you may need to uninstall the app before installing this build.
- Open "Settings" dialog and activate the "Developer options" an the end of the settings list
- Go back to the app. An application menu (three dots on the left of toolbar) appears.
- Go to the radio station list and rotate the device. Go to the radio station again. How I understood, the list is empty, correct?
- Press the application menu button and select the menu "Latest logging"
- Long press on the text and than press "Select All" from context menu
- Copy this text in buffer ("Copy" from the context menu) and send it me per e-mail (do not attach it here)
- Open "Settings" dialog again and DISABLE the "Developer options"

**Comment by iamchriscool** [comment] 2019-05-05 18:58
Hi @mkulesh, I've installed the debug version of the app, reproduced the problem with the empty station list (what happens less with this version after rotating the screen), opened the log dialog, selected a word by long press on the text, but I don't get a menu for selecting all text or copy the selected text, no context menu at all.
But I saw in the log messages that the problem with the empty list comes from the automatic disconnection to my receiver after rotating. The log says "MainAcivity: device disconnected".
So it seems to me there is (re-)connection problem after rotation. Is it maybe possible to keep the connection open?

**Comment by mkulesh** [comment] 2019-05-12 20:12
Hi @iamchriscool, the missed context menu is strange since it is basic Android functionality, see screenshot from my Android 8 below. If this does not work on your phone, could you please collect the logging using ADB as described here: https://github.com/mkulesh/onpc/wiki?

"MainAcivity: device disconnected" is a desired behavior. This corresponds to the life-cycle of the Android app. If device is rotated, the app will be first suspended by the Android OS with optional state collection, and than will be started from scratch where the previously collected state is passed as the argument. Since my app does nut support background handling, I shall disconnect the remote device when app is suspended and the logging show it. I believe the problem with the empty station list is easy, but I need logging for it.
 
![contextMenu](https://user-images.githubusercontent.com/30557348/57587233-1b4e2000-7502-11e9-965b-3660caaa573e.png)

**Comment by mkulesh** [comment] 2019-05-12 20:19
Hi @quelbs, if you are able to reproduce the problem with empty station list after device rotation, as well as the missed green arrow marker, could you maybe collect and send me the log an and some screenshots?

**Comment by mkulesh** [comment] 2019-08-17 20:22
Hi @iamchriscool,
now I changed the app behavior on device rotation. The app keeps now the connection when device orientation changed. I hope the problem is solved, could you please test?

**Comment by mkulesh** [comment] 2019-09-05 19:37
Released in version 1.3

**Closed by mkulesh** 2019-09-05 19:37 UTC
Labels: bug
