### ISSUE TITLE
Deezer search for Denon HEOS is missing

### ISSUE THREAD

**Issue by Joska59** [mkulesh/onpc#290] opened 2023-12-30 18:29 UTC
Hi
Today is the first time, emc has found my receiver ;-)
Now, I tried to listen to dab-radio. Well, but only approx 15 stations.
Then tried to use Deezer. It is possible to connect to stored playlists, but seems to be impossible to search inside Deezer, looking for titles or artists.
Maybe, I'm blind, haven't found this feature.
Jumping out into Deezer-app starting this search and playing songs is okay, but with this way, every message incoming, stops music playing for 2-3 seconds.
Is it possible to use Deezer from inside emc?
At last, nice app, seems to be so much more comfortable then the original Heos-app.
Thank you. Joerg

**Comment by mkulesh** [comment] 2023-12-30 18:50
Hi @Joska59 
Which receiver model do you have? For all brands that I testet (Onkyo, Pioneer, Denon) Deezer is fully supported inside the app:
1. Deezer shall be visible in the list of network services
![deezer1](https://github.com/mkulesh/onpc/assets/30557348/ce053532-7ce1-4270-b52e-9c7a3bc262f0)
2. If you select Deezer, it allows full navigation in the media library:
![deezer2](https://github.com/mkulesh/onpc/assets/30557348/d1335af0-a2ea-4de1-af29-d9248dc51368)

Of course, you shall have the premium (payed) Deezer account and login into this account in your receiver. If you have Denon device, please use official HEOS app to do it. For Onkyo and Pioneer, select the last item Login in the Deezer list in my app and fill the login and password form afterward. You can also lodin into Deezer using official Onkyo/Pioneer apps.

**Comment by Joska59** [comment] 2023-12-30 19:09
Hi @mkulesh 
I use a denon dra-800h. As I remember, you do the same.
I can see all items on your picture, but how is it possible to search for artists or titles?

**Comment by mkulesh** [comment] 2023-12-30 19:16
Hi @Joska59,
first of all, install the official Denon HEOS app (https://play.google.com/store/apps/details?id=com.dnm.heos.phone) and perform the login into Deezer from this app. Your dra-800h shall be logged in into your personal Deezer account. 

After it, you will be able to navigate in your Deezer library:
![deezer3](https://github.com/mkulesh/onpc/assets/30557348/726b12c5-ee05-4c56-b95c-ac6fd8491bce)

**Comment by Joska59** [comment] 2023-12-30 20:29
> Hi @mkulesh

The heos-App is installed since i've bought the DRA-800H. The account-data has been filled in the same time. As I said, I can see all my music data, but can't search. May be, I'm blind :-)
Don't want to stress you, I'Ll try it again tomorrow.

**Comment by Joska59** [comment] 2023-12-31 11:50
Hi
Some more experiments. I use the latest version of deezer, see all playlists and albums, but, I can't find any menu to login. As I remember well, I did it sooner years ago and the fact, I never been disturbed by advertising, it's a hint for a professional account.
Inside your app, I see the same lists and features, like in heroes. 
![Screenshot_20231231_123922_Enhanced Music Controller](https://github.com/mkulesh/onpc/assets/115286175/12a6b966-2078-469d-a95f-5b2467fb1351)
![Screenshot_20231231_123945_HEOS](https://github.com/mkulesh/onpc/assets/115286175/f4c750b6-d1a3-4a0c-8d26-766911219f35)

On Heos app, I see the magifying glass right button, this leads to search. On your app, after I opened the deezer submenu, I see filter-icon right up, but clicking on it and pasting any title or author, never leads to a result.

Wrong behaviour of the user?

Some more, I jump back from filtering with the little error left in the same line, I don't go back to deezer, but to the root menu. Correct? I had expected being in deezer-main-menu again.

At last, if I choose one of playlists, start the first song, it does not play the next after ending the first, but jumps into a list in background.
How to play only this playlist, nothing less, nothing more, without collecting every song after another?

**Comment by mkulesh** [comment] 2023-12-31 12:43
Hi, thank you for detailed description. Now I see that you mean with search. 
- Deezer search behavior is different on the different receiver brands. The search works at the moment for Onkyo/Pioneer. For Denon, some additional implementation on my site is missing. I will inspect the HEOS documentation and will try to add the search in the next release.
- Filter-icon right up is only local filter that allows to reduce a huge list, not more.
- I am not sure that you mean with "jump back from filtering with the little error left in the same line". The top-left arrow button in the same line like filter button means jump to NET top. If you use this button yes, it is correct that the root menu appears.
- The simplest way to play a Deezer playlist is following: to to Deezer -> My Playlists and long press on a playlist you want to play (do not go inside the playlist). A context menu appears. Than select "Replace and play". 
![deezer4](https://github.com/mkulesh/onpc/assets/30557348/c879a8bb-87f5-48e2-8929-c008b3abb86f)

- Receiver will copy whole playlist into NET -> Play Queue and it will be played in the same order as listed in Play Queue. You can reorder items by drag-and-drop on the "two lines" icon in the left on each line. 
![deezer5](https://github.com/mkulesh/onpc/assets/30557348/2406cc47-c4c8-40ad-955d-74b95ee2d37a)

- The "Random" button in the LISTEN tab can change this behaviour, if "Random" mode is active, Play Queue will be played in the random order.

**Comment by mkulesh** [comment] 2023-12-31 12:53
Developer notice:
The search in HEOS is implemented by two commands:
- 4.4.5 Get Source Search Criteria
Command: heos://browse/get_search_criteria?sid=source_id
- 4.4.6 Search
Command: heos://browse/search?sid=source_id&search=search_string&scid=search_criteria&range=start#, end#

**Comment by Joska59** [comment] 2023-12-31 13:07
The changed title is much better, then the initial one. Thank you.

**Comment by mkulesh** [comment] 2024-01-04 21:07
Hi @Joska59,
the search is now added. Please use "Magnifier" icon in the top-right corner:
![search](https://github.com/mkulesh/onpc/assets/30557348/4e72e375-10f6-4d60-801b-8708212ccb5d)
It works not only for Deezer, but also for all other network services and local music.

Please download and manually install the development build from here: https://1drv.ms/u/s!At2sh2-YDyGFgwFQwlFnt-q1JyeD?e=FKZaWt

Please note that this build is not yet fully tested, i.e some new errors may appear.

**Comment by Joska59** [comment] 2024-01-05 13:09
Hi

Package installation canceled several times.

Don't know, what to do next. Error log?

**Comment by Joska59** [comment] 2024-01-05 15:00
Okay, found the cause.  Installation from the file explorer was not allowed.  After uninstalling the Playstore version, you can then, but only then, notice the lack of authorization.
 With permission I was able to install and search :-)

 But when I then want to send these search results to the queue, nothing happens.

 It's also irritating when I've searched several levels down in the hierarchy but haven't found anything and then want to go back to the top level again.  Maybe this can be done at the system level.  I will test it.

 At the moment my Denon Home 150 keeps playing the songs selected before installation and ignores my search.

Okay, habe die Ursache gefunden. Aus den Dateiexplorer war die Installation nicht erlaubt. Nach Deinstallation der Playstore-Version kann dann, aber erst dann, der Hinweis auf die fehlende Berechtigung.
Mit erteilter Erlaubnis konnte ich installieren und auch suchen :-)

Aber, wenn ich dann diese Suchergebnisse in die Warteschlange schicken will, passiert.... Nix.

Weiterhin ist es irritierend, wenn ich mehrere Hierarchiestufen tief gesucht, aber nichts gefunden habe, und dann zurück will, wieder in der obersten Ebene bin. Vielleicht geht das ja auf Systemebene. Ich werde es testen.

Im Moment spielt mein Denon Home 150 weiter die vor der Installation ausgewählten Songs und ignoriert meine Suche.

**Comment by mkulesh** [comment] 2024-01-05 17:18
Hi @Joska59 
I tested the search on Deezer, Local Music and TuneIn and I can start to play both separate songs and albums. Could you please provide more details:
- In which service do you search? In Deezer?
- Which string do you search? Could you please also take a screenshot with search results for this string?
- Which song or album do you send to queue?

**Comment by Joska59** [comment] 2024-01-05 18:03
Hi
I'd searched in Deezer, found "Ronan Keating", openend one folder after another, rhen at last, tried to put the one above, 10..,to the queue, but nothing happens
![Screenshot_20240105_185928_Enhanced Music Controller](https://github.com/mkulesh/onpc/assets/115286175/ae391303-f302-49b5-b4da-92991d9b05c8)
![Screenshot_20240105_190005_Enhanced Music Controller](https://github.com/mkulesh/onpc/assets/115286175/1918948a-9c71-4e32-93c4-4f652452e613)
![Screenshot_20240105_185944_Enhanced Music Controller](https://github.com/mkulesh/onpc/assets/115286175/f03079cc-944a-4d51-81c4-40eea6069257)

**Comment by Joska59** [comment] 2024-01-05 18:13
okay,  some more information. The information was filled up to the queue in background, if I open the queeu bei hand, I find all selecteted songs and can start them inside the queue.

intuitiv, I had imagined, the start should habe been done after selecting inside deezer saerch, in the same way, it happend, if I'd selected an album from my lists.

**Comment by Joska59** [comment] 2024-01-05 18:17
Next: I use both varaints of the app at the same time, to see the differences. Actually, the bet-version does not increase the noise, the original one from play store (not payed) does.

**Comment by mkulesh** [comment] 2024-01-05 18:34
Thanks! If a search Ronan Keating, go to Ronan Keating -> Albums -> 10 Years of Hits and than press on Lovin' Each Day, the song is added into the play queue and immediately started to play. This is as desired. 

The same, if I go to Ronan Keating -> Albums, long press on "Destination" and than select Replace and Play, the whole album is added into the queue and immediately started to play. It is also as desired. However, I tested it for main Zone. You use the Zone2. Could you please try the same for main zone? Or maybe your queue is too long that the receiver is not more able to handle it correctly? Please try to erase the queue: long press on any item in the queue and than "Remove all".

I'm am not sure, but that do you mean with "does not increase the noise"?

**Comment by mkulesh** [comment] 2024-01-05 19:07
I also tested it for Zone2 too. The single click on a song and long click on an album and than "Replays and play" work as desired - item(s) are added into queue and playing is started. Could you please describe your steps more precise, where the song is placed into queue but playing is not started? I would like to reproduce it.

**Comment by Joska59** [comment] 2024-01-05 19:11
Yes, as you described it, I would have expected, but  in beta-app, it doesn't.

With increasing the noise, I meant, the volume  does not increase by using the buttons or the hardware buttons of my phone,  using the beta-app, only inside the original app from playstore, volume in/decreases-

**Comment by mkulesh** [comment] 2024-01-05 19:11
> It's also irritating when I've searched several levels down in the hierarchy but haven't found anything and then want to go back to the top level again. Maybe this can be done at the system level. I will test it.

The "Back" button returns to the same level where the search was performed. There is an addition button in the top-left corner (bold top-left arrow) that can be used if you want to go to the top level.

**Comment by mkulesh** [comment] 2024-01-05 19:24
Strange...
I rebuild the app, please find new build here: https://1drv.ms/u/s!At2sh2-YDyGFgwIA78bxLl3AmXDk?e=S0HL0C
Please manually uninstall previous version before installing this new build. 
For volume control please inspect the application settings and ensure that the "Sound control" parameter is set to "Automatic" or any of "Device..."

**Comment by Joska59** [comment] 2024-01-05 19:24
Start situation: Music is played via the loudspeaker in Zone2 (Farfarello), then I start a search in EMC/Deezer for Andreas Vollenweider. I search in the list of albums and then add an album to the queue.
Zone2 is selected, the list is filled properly, but nothing is played.

**Comment by Joska59** [comment] 2024-01-05 19:26
Okay, see, a new version, I'll test it. New day, new answers tomorrow :-)

**Comment by mkulesh** [comment] 2024-01-05 19:30
> Vollenweider. I search in the list of albums and then add an album to the queue.
Zone2 is selected, the list is filled properly, but nothing is played.
If you use the command "Add" from the context menu, the album is only added into queue. In order to add and start playing, you should use "Replace and play" or "Add and play". Which context menu command do you use?

**Comment by Joska59** [comment] 2024-01-05 20:54
I'd used replace&play

Am 5. Januar 2024 20:30:15 schrieb Mikhail Kulesh ***@***.***>:

**Comment by Joska59** [comment] 2024-01-07 13:49
Hello Mikael
I still have various problems using the app. Starting with the last version 2.13.2 now works reliably if the receiver is supplied with power for> 1 minute.
What doesn't work for me at the moment is the assignment to Main Zone and Zone2.
I start the app, choose the main zone there and then start playing the current song, which is in the current list on the 2nd. Screen can be seen.
Now the app plays this song in Zone2, but it stays there so that I cannot change the volume. I can change this in the APP and with the volume keys, but this has no effect on the real volume at Denon Home 150 ~ Zone2.

Now I am currently being offered an update for the DRA-800H, which is now really starting for the first time. then I wait and see what shows up afterwards.

Okay, after update, the volume-control seems to be correct again.
Is it correct, that I only can choose one zone to play music, not both together?


Hallo Mikael
ich habe weiterhin diverse Probleme bei der Nutzung der App. Das Starten mit der letzten Version 2.13.2 funktioniert jetzt zuverlässig, wenn der Receiver > 1 Minute mit Strom versorgt ist.
Was im Moment bei mir gar nicht funktioniert, ist die Zuordnung zu Main Zone und Zone2.
Ich starte die App, wähle dort die Main Zone und starte dann das Abspielen des aktuellen Songs, der in der aktuellen Liste auf dem 2. Screen zu sehen ist.
Nun spielt die App diesen Song in Zone2 ab, dort bleibt es aber so, dass ich die Lautstärke nicht ändern kann. Ich kann diese in der APP und mit den Lautstärketasten zwar verändern, aber dies hat keine Auswirkung auf die reale Lautstärke am Denon Home 150 ~ Zone2.

Nun wird mir gerade zum x-ten mal ein Update für den DRA-800H angeboten, welches nun erstmalig wirklich startet. dann warte ich mal ab, was sich danach zeigt.

Okay, nach dem Update scheint die Lautstärkeregelung wieder korrekt zu sein.
Ist es richtig, dass ich nur eine Zone auswählen kann, um Musik zu spielen, nicht beide zusammen??

**Comment by Joska59** [comment] 2024-01-07 14:01
Oops, now it's getting more and more complicated. Suddenly I get the message that I don't have a Heos account, Deezer reports, no more streaming possible. (it doesn't be that it looks like Deezer is opening multiple sessions?)
However, I am logged in to the Heos app with my account details.

I will simply log everything off and log in again and then look again later in peace.
Ups, nun wird es immer komplizierter. Plötzlich erhalte ich die Meldung, kein Heos-Konto zu haben, Deezer meldet, keine Streaming mehr möglich. (kein es sein, dass es für Deezer so aussieht, als würde ich mehrere Sessions öffnen?)
In der Heos-App bin ich jedoch mit meinen Kontodaten angemeldet.

Ich werde einfach mal alles ab- und wieder anmelden und dann später noch einmal in Ruhe schauen.

**Comment by Joska59** [comment] 2024-01-07 19:15
Heos-Problem: Heos has logged me out, without any hint. After extraordinary loggout by hand and re-login, deezer function was well again. Shit happens, first time in 2 years.

Heos-Problem: Heos hat mich ohne Hinweis abgemeldet. Nach außergewöhnlichem Loggout von Hand und erneuter Anmeldung war die Deezer-Funktion wieder gut. Mist, passiert zum ersten Mal seit 2 Jahren.

**Comment by mkulesh** [comment] 2024-01-07 20:24
Hi @Joska59 

> Okay, after update, the volume-control seems to be correct again. 

Correct, I planned to ask you about firmware version since it is really important always have the actual firmware.

> Is it correct, that I only can choose one zone to play music, not both together?

It depends... In the Zone2, there is an input channel called "SOURCE". It propagates the music from the main zone to zone 2, i.e the same source in main zone is playing for both zones. Some input channels allows to play different music in both zones, please refer to receiver user manual for details. And yes, the volume control is always per its zone, i.e the change for the main master volume shall have NO impact on the zone 2 master volume.

> Heos has logged me out, without any hint. After extraordinary loggout by hand and re-login, deezer function was well again. Shit happens, first time in 2 years.

I had the same problems two days ago... I also shall re-login, not in HEOS, but in Deezer as well. It seems to be Denon has remotely triggered re-login for some its models... 

> I'd used replace&play
How it now works in the latest build? Could you please try the following:
- For the HEOS source, select "Play Queue". 
- Long press on any item and select context menu "Remote all". The Play Queue shall have no items after it.
- Select Deezer and search Artist "Sons and Daughters". 
- Navigate to "Sons and Daughters" -> "Albums". 
- Long Press on "The Repulsion Box" and select "Replace and Play". Does the playback start automatically or not?

**Comment by Joska59** [comment] 2024-01-12 19:27
Hello Mikael
At the moment I am not coming to test for professional reasons, but I will report again later.


Hallo Mikael
Zur Zeit komme ich aus beruflichen gründen nicht zum testen,  melde mich aber später wieder.

**Comment by Joska59** [comment] 2024-01-17 16:04
Hello Mikael
Now I have a little time again. Playing a waiting list directly works. Great.
If I now activate Zone2 as a media ** Source **, I would have expected the same music to be played here as under Zone1, but the speaker remains silent.

After I have pushed the two rooms, living room = DRA-800H and kitchen = Denon home 150, together in the original Heos app, the same music from all speakers finally sounds. Without this measure, the Denon home remains silent.

If I now set zone1 = main zone in your app, I can control the volume of the speakers connected directly to the DRA in the app, then I switch to Zone2, this speaker does NOT react to the volume control, even if I am careful, remains the volume the same.

German
Hallo Mikael
Nun habe ich wieder ein bisschen Zeit. Das direkte Abspielen einer Warteliste funktioniert. Prima.
Wenn ich nun die Zone2 aktiviere, als Medien **Source** wähle, hätte ich erwartet, dass auch hier die gleiche Musik abgespielt wird, wie unter Zone1, aber der Lautsprecher bleibt stumm. 

Nachdem ich in der original Heos-App die beide Räume, Wohnzimmer=DRA-800H und Küche=Denon home 150, zusammengeschoben habe, erklingt auch endlich die gleiche Musik aus allen Lautsprechern. Ohne diese Massnahme bleibt der Denon home stumm.

Wenn ich nun in deiner App auf zone1=main zone stelle, kann ich in der App die Lautstärke der direkt am DRA angeschlossenen Lautsprecher steuern, wechsel ich dann auf Zone2, reagiert dieser Lautsprecher NICHT auf die lautstärkeregelung, selbst wenn ich auf mute stelle, bleibt die Lautstärke gleich.

**Comment by mkulesh** [comment] 2024-01-18 21:23
Hi @Joska59,

Please refer to the receiver user manual: https://manuals.denon.com/dra800h/EU/EN/WBSPSYwadwfjyg.php

Zone2 is represented by a _physical_ output "PRE OUT Zone2" on the back plane of the receiver. As I understand, in order to use it, an _amplifier_ shall be attached to this output. Actually it is new for me that it is possible to pair this output with an external HEOS speaker... Please correct me if I wrong.

From my point of view, the Zone2 volume control in the app belongs to this output only and has NO affect on any devices paired via HEOS. The volume on the external HEOS speaker shall be changed if you connect to this speaker directly via HEOS app since my app does not yet support such a speakers.

Anyway, this question does not belong to the issue theme. Please ask such a questions via Email on mikhail.kulesh@gmail.com

**Comment by mkulesh** [comment] 2024-03-27 22:25
Released in version 1.32

**Closed by mkulesh** 2024-03-27 22:25 UTC
Labels: enhancement
